### PR TITLE
test: Run HTTP Server TCK for Azure HTTP Function 

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
@timyates Could you take over from me this task? The idea is to run the server TCK against Azure HTTP Functions. If we need to do breaking chagnes please change the base to `master`

**Comment by timyates** [comment]
The TCK isn't a thing till Micronaut 3.8.x, so this will need a micronaut update from 3.7 -> 3.8 (which will imply a new minor version of this module)

**Comment by timyates** [comment]
Actually, it looks like we've already released 3.8.0 which still points to Micronaut 3.7.4

So this would need to be for 3.9.0?

**Comment by sdelamo** [comment]
> Actually, it looks like we've already released 3.8.0 which still points to Micronaut 3.7.4
> 
> So this would need to be for 3.9.0?

Ideally, I would like the TCK to be run against a branch compatible with 3.x. 3.9.x is ok.

**Comment by timyates** [comment]
Superseded by https://github.com/micronaut-projects/micronaut-azure/pull/437 on the correct branch

**Pull request closed without merging**
