### PR TITLE
Fix: Prevent global context reset per Azure Function invocation

### PR DESCRIPTION
**Pull request by alejojarahi**
Solution for the problem of the application context since it is being reset for each invocation of the function, and should be global for its life cycle. https://github.com/micronaut-projects/micronaut-azure/issues/688

A check is included to prevent create an AzureHttpFunction bean per execution.

### CODE REVIEW

**Comment by graemerocher** [comment]
seems to cause test failures

**Comment by alejojarahi** [comment]
@graemerocher I already updated the PR with the correction. Additionally, I included a fix to another behavior that occurs with the azure function in Micronaut https://github.com/micronaut-projects/micronaut-azure/issues/696

**Comment by graemerocher** [comment]
Still failing

**Comment by alejojarahi** [comment]
@graemerocher Hello, corrected (I identified a behavior change when synchronizing the fork, which involved updating the new test added). Thanks

**Comment by graemerocher** [comment]
Thanks for the contribution

**Pull request merged**
